### ISSUE TITLE
error: no viable overloaded '='

### ISSUE THREAD

**Issue by ryandesign** [plibither8/2048.cpp#122]
Hi, we have [2048.cpp in MacPorts](https://ports.macports.org/port/2048.cpp) and it builds fine on OS X 10.11 and later, but on [OS X 10.10 it fails to build](https://build.macports.org/builders/ports-10.10_x86_64-builder/builds/116178/steps/install-port/logs/stdio). There are many errors in the log but the first is:

```
src/game-pregamemenu.cpp:139:42: error: no viable overloaded '='
  std::tie(loaded_gameboard, tempGBoard) =
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/tuple:500:29: note: candidate function (the implicit move assignment operator) not viable: no known conversion from 'tuple<bool, struct GameBoard>' to 'tuple<std::initializer_list<bool> &, Game::GameBoard &>' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY tuple
                            ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/tuple:500:29: note: candidate function (the implicit copy assignment operator) not viable: no known conversion from 'tuple<bool, struct GameBoard>' to 'const tuple<std::initializer_list<bool> &, Game::GameBoard &>' for 1st argument
class _LIBCPP_TYPE_VIS_ONLY tuple
                            ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/tuple:692:26: note: candidate template ignored: disabled by 'enable_if' [with _Tuple = std::__1::tuple<bool, Game::GameBoard>]
                         __tuple_assignable<_Tuple, tuple>::value
                         ^
```
